import streamlit as st
import os
import google.generativeai as genai

# Get Google API key from environment variable
os.getenv("GOOGLE_API_KEY")
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

# Set page configuration
st.set_page_config(page_title="BizGen GPT", page_icon="images/logo.png")

# Define industries with corresponding images
INDUSTRIES = {
    "Technology": "🔧",
    "Healthcare": "⚕️",
    "Education": "📚",
    "Retail": "🛒",
    "Finance": "💰",
    "Food & Beverage": "🍔",
}

# Function to get Gemini response
def get_gemini_response(question):
    """
    Function to generate a response using Gemini model.
    
    Args:
        question (str): The question or prompt for which response is generated.
        
    Returns:
        str: The response generated by the Gemini model.
    """
    model = genai.GenerativeModel('gemini-pro')
    response = model.generate_content(question)
    return response.text

# Function to create navigation bar
def navbar():
    """
    Function to create the navigation bar on the sidebar.
    
    Returns:
        str: The selected page from the navigation options.
    """
    st.sidebar.title("Navigation")
    st.sidebar.header("BizGen GPT")
    st.sidebar.markdown("Choose an option:")
    page = st.sidebar.radio("Select Page", ["Home", "About"])
    return page

# Function to create header
def header():
    """
    Function to create the header section of the page.
    """
    st.title("Welcome to BizGen GPT!")
    st.subheader("BizGen GPT: Empowering Entrepreneurs with AI-Driven Business Ideas and Create a Business Plan!")

# Function to create footer
def footer():
    """
    Function to create the footer section of the page.
    """
    st.markdown("---")
    st.write("BizGen GPT - Powered by Streamlit & OpenAI")
    st.write("Final Project in CCS 229 - Intelligent Systems")
    st.write("Ma. April G. Suarnaba BSCS 3B AI")
    st.write("© 2024 All rights reserved")

# Function to display about section
def about_section():
    """
    Function to display the about section of BizGen GPT.
    """
    st.title("About BizGen GPT")
    st.write("BizGen GPT is a cutting-edge web application powered by OpenAI's GPT model, designed to revolutionize the way entrepreneurs and business enthusiasts generate innovative business ideas. With BizGen GPT, users can harness the power of artificial intelligence to explore various industries, target audiences, and unique selling points, enabling them to uncover new opportunities and drive business growth.")
    st.title("Mission")
    st.write("At BizGen GPT, our mission is to empower aspiring entrepreneurs and business leaders with the tools and knowledge they need to transform innovative ideas into successful ventures. We aim to foster creativity, drive innovation, and facilitate collaboration in the entrepreneurial ecosystem, ultimately contributing to sustainable economic development.")
    st.title("Vision")
    st.write("Our vision is to create a dynamic and supportive platform where individuals from diverse backgrounds can unleash their entrepreneurial potential and realize their dreams of building impactful businesses. We envision BizGen GPT as a catalyst for positive change, inspiring a new generation of innovative thinkers and problem solvers.")
   
    st.title("How to Use:")
    st.write("1. Select Industry: Choose from a range of industries, including Technology, Healthcare, Education, Retail, Finance, and Food & Beverage.")
    st.write("2. Choose Target Audience: Specify your target audience, such as Young Professionals, Elderly, Students, Small Businesses, or Large Corporations.")
    st.write("3. Provide Unique Selling Points: Share your unique selling points or innovations for your chosen industry and target audience. ")
    st.write("4. Generate Business Idea: Click the Generate Business Idea button to unleash the power of AI and receive a tailored business idea based on your inputs.")

# Main content
def main():
    """
    Main function to run the Streamlit application.
    """
    page = navbar()

    if page == "Home":
        header()
        st.subheader("Generate Your Next Big Idea")
        industry = st.selectbox("Select an industry:", list(INDUSTRIES.keys()), format_func=lambda x: f"{INDUSTRIES[x]} {x}")

        if industry:
            target_audience = st.selectbox("Select target audience:", ["Young Professionals", "Elderly", "Students", "Small Businesses", "Large Corporations"])

        if target_audience:
            unique_points = st.text_input(f"What unique selling points or innovations do you have for {target_audience} in the {industry} industry?")

        if unique_points:
            prompt = (f"Generate a business idea in the {industry} industry targeting {target_audience}. "
                      f"The unique selling points or innovations include: {unique_points}.")

            if st.button("Generate Business Idea"):
                st.subheader("Your Business Idea")
                business_idea = get_gemini_response(prompt)
                st.write(f"🚀 **{business_idea}**")

    elif page == "About":
        about_section()

if __name__ == "__main__":
    main()
    footer()
